repo:
  add-topic:
    - terraform
    - azure
    - azurerm_container_registry
  default-branch: main
  delete-branch-on-merge: true
  description: A Terraform module that manages the container resources from the azurerm provider.
  visibility: public
