---
name: github

on: [push]
  # schedule:
  #   - cron: '00 10 * * *'
  # push:
  #   paths:
  #     - '.github/settings.yaml'

# jobs:
#   call-github:
#     uses: T-Systems-MMS/.github/.github/workflows/github.yml@github_settings

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up yq
        uses: frenck/action-setup-yq@v1

      - name: gh repo edit
        run: |
          # add-topic must be splittet into one command for each topic
          yq '.repo | with_entries(select(.key != "add-topic"))' .github/settings.yaml | tr -d : >  gh_repo
          yq '.repo | with_entries(select(.key == "add-topic")) | to_entries | .[].value[] | sub("(.*)", "add-topic ${0}")' .github/settings.yaml >>  gh_repo

          # get and set settings
          cat gh_repo | while read repo_cmd; do echo "gh repo edit ${GITHUB_REPOSITORY} --$repo_cmd" && gh repo edit ${GITHUB_REPOSITORY} --$repo_cmd; done
        env:
          GH_TOKEN: ${{ secrets.GH_CLI_TOKEN }}
