---
name: test

on: [pull_request]

env:
  TEMPLATE_REPOSITORY: T-Systems-MMS/terraform-template

jobs:
  call-test:
    if: github.repository != '$TEMPLATE_REPOSITORY'
    uses: T-Systems-MMS/.github/.github/workflows/terratest.yml@main
    with:
      test: azure
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
